#!/bin/bash

function check_user() {
	user="${1}"
	if [ "$(grep "${user} " /etc/wireguard/clientlist.txt)" == "" ]; then
        	echo "remove user ${user}"
        	peer="$(cat /etc/wireguard/clients/${user}/${user}.pub)"
        	wg set wg0 peer ${peer} remove
	fi
}

pushd /etc/wireguard/clients/ 
for c in $(ls -1); do
	check_user ${c}
done
popd

echo "Restart wireguard:"
systemctl restart wg-quick@wg0 && echo "restart completed" && exit 0
echo "restart FAILED"
exit 1
