#!/bin/bash

for l in $(cat /etc/wireguard/clientlist.txt | sed 's/ /#/g'); do
  name="$(echo ${l} | cut -d '#' -f 1)"
  peer="$(echo ${l} | cut -d '#' -f 2)"
  echo -n "${name} - "
  wg show | grep -A 100 ${peer} | sed '/^$/q'
done
