#!/bin/bash

if [ $# -eq 0 ]; then
  clear
  cat /etc/wireguard/clientlist.txt | cut -d " " -f 1
  read -p "Enter Name (Enter empty name to abort): " name
  if [ "${name}" = "" ]; then echo "abort" && exit 0; fi
else
  name=${1}
fi

if [ "$(cat /etc/wireguard/clientlist.txt | grep ${name} | wc -l)" != 1 ]; then
  echo "Name not found or name not unique"
  exit 1
fi

peer="$(cat /etc/wireguard/clientlist.txt | grep stoffi | cut -d ' ' -f 2)"

wg set wg0 peer ${peer} remove
echo $?

tmp=$(mktemp)
cp /etc/wireguard/clientlist.txt ${tmp}
grep -v ${name} ${tmp} > /etc/wireguard/clientlist.txt
cat /etc/wireguard/clientlist.txt | cut -d ' ' -f 1
